### ISSUE TITLE
Output data showing NULL 

### ISSUE THREAD

**Issue by mhabid98** [shahariaazam/DSE-Share-Market-Update#5]
I am using this ( https://github.com/shahariaazam/DSE-Share-Market-Update ) plugin on WordPress. Everything is working fine but for a few days the data output showing null

https://s33.postimg.cc/518pdqt67/screenshot_1044.png
https://s33.postimg.cc/sfgopqg9b/screenshot_1045.png
https://s33.postimg.cc/5e03k0qwf/screenshot_1046.png

**Comment by shahariaazam** [comment]
@mhabid98 the problem already fixed in the last commit https://github.com/shahariaazam/DSE-Share-Market-Update/commit/4fec688d0a140af3ecc1f7fc1d109e4c234b9578

http://www.dsebd.org has already activated SSL on their site. So you just need to change the url from `http` to `https` and it will fix the issue.

**Comment by mhabid98** [comment]
I have changed it but it's not working. I have downloaded a fresh copy and add it to localhost now it's showing another issue. https://s33.postimg.cc/xgu1qtmq7/screenshot_1047.png
